export { default as RootFirstFrame } from "./frames/root" 
export { default as PotdFirstFrame } from "./frames/potd" 
export { default as ResourcesFirstFrame } from "./frames/resources" 
export { default as PastExamsFirstFrame } from "./frames/pastexams"
export { default as LoginFirstFrame } from "./frames/login" 
